name: CI

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  actions: write

jobs:
  merge-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Merge dev to test
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            
            # Check if test branch exists on remote
            if git ls-remote --exit-code --heads origin test; then
              echo "Branch test exists, checking out"
              git fetch origin test
              git checkout -B test origin/test
            else
              echo "Branch test does not exist, creating it"
              git checkout -b test
            fi
        
            # Merge dev into test
            if ! git merge origin/dev --no-commit; then
              echo "Merge conflict detected, resolving in favor of dev branch changes"
              git checkout --theirs .
              git add .
            fi
        
            git commit -m "Merge dev into test" || echo "No changes to commit"
            
            # Use token for authentication when pushing
            git remote set-url origin https://x-access-token:${{ secrets.WORKFLOW_TOKEN || secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin test

  run-tests:
    runs-on: ubuntu-latest
    needs: merge-to-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Set up Ruby (auto-detect from .ruby-version or Gemfile)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: List available Rake tasks
        run: rake -T

      - name: Run tests
        run: rake test
