name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
      
      - name: Run tests
        run: bundle exec rake test
      
      - name: Get version from gemspec
        if: github.ref == 'refs/heads/main' && success()
        id: gemspec_version
        run: |
          VERSION=$(ruby -e "require './snakommit.gemspec'; puts Gem::Specification::load('./snakommit.gemspec').version")
          echo "::set-output name=version::v$VERSION"
      
      - name: Create and push tag
        if: github.ref == 'refs/heads/main' && success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git tag ${{ steps.gemspec_version.outputs.version }}
          git push origin ${{ steps.gemspec_version.outputs.version }}
      
      - name: Build gem
        if: startsWith(github.ref, 'refs/tags/') && success()
        run: gem build *.gemspec
      
      - name: Publish to RubyGems
        if: startsWith(github.ref, 'refs/tags/') && success()
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem push *.gem

