name: CI

on:
  push:
    branches:
      - dev

jobs:
  merge-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge dev to test
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout test
          git merge dev
          git push origin test

  run-tests:
    runs-on: ubuntu-latest
    needs: merge-to-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Run tests
        run: |
          bundle install
          rake test