name: CI

on:
  push:
    branches:
      - dev

jobs:
  merge-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge dev to test
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Check if test branch exists, create it if not
          if git ls-remote --heads origin test | grep test; then
            echo "Branch test exists, checking out"
            rm -rf test
            git checkout test
          else
            echo "Branch test does not exist, creating it"
            rm -rf test
            git checkout -b test
          fi
          
          git merge dev
          git push origin test

  run-tests:
    runs-on: ubuntu-latest
    needs: merge-to-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Debug available rake tasks
        run: |
          bundle install
          rake -T
          
      - name: Run tests
        run: |
          rake test